### ISSUE TITLE
Lack of/very slow convergence in some cases when setting cost_limit to infinity

### ISSUE THREAD

**Issue by Bram94** [gatagat/lapjv#4]
First of all, thanks for this implementation of the Jonker-Volgenant algorithm! I have implemented it in a storm-tracking algorithm.

When using the LAPJV implementation with a finite cost_limit, everything works fine. When removing this limit however, there are a few cases in which it does not converge to a solution. Because I found that using the algorithm without the cost_limit is much faster than with it, I prefer to use it without the cost_limit. In this case I set the cost for unallowed associations to a very high value, such that they won't be performed before all allowed associations are made. I can then remove the unallowed associations afterwards.

Currently this method does not work however, because the cases with a lack of convergence make the method unreliable. Do you have ideas about how to overcome this lack of convergence?

**Comment by gatagat** [comment]
Could you provide a minimal example reproducing the error?

**Comment by gatagat** [comment]
The `cost_limit < inf` is handled by adding dummy nodes enlarging the cost matrix to `(2*N, 2*N)`. What is the size of your typical problem?

BTW, there is a fairly ready implementation of the same algorithm for sparse matrices `lapmod` where the cost size grows only linearly. So especially for large sparse problems, it might work a lot faster.

**Comment by Bram94** [comment]
I currently do not have a cost matrix that leads to lack of convergence at hand, but will post the one that most recently lead to the problem tomorrow. And if it is unreasonably large, I will try to find a suitable smaller one.

I did already try the lapmod implementation, but in its current form it appeared to be unsuited for my purpose, for a reason that I do not remember at the moment. I will also check that tomorrow.

**Comment by Bram94** [comment]
BTW, my cost matrices are generally not square, and I am pretty sure that that was the reason that the lapmod implementation is currently unsuited for my purpose.

**Comment by gatagat** [comment]
One can use it for non-square matrices as well, after appropriately extending them. This is implemented for `lapjv(..., extend_cost)` but it is not there yet for lapmod.

Try something similar to [this code](https://gist.github.com/gatagat/98a1deb9f855c446fb497db1b6a83e96).

**Comment by Bram94** [comment]
Thanks for that. I hadn't taken the time to do it myself when testing it previously. I will implement it tomorrow, and will mention the results.

**Comment by Bram94** [comment]
Using the lapmod implementation with the extension works properly, except that it has the same problem of a lack of convergence in a few cases. Unfortunately, I haven't found a suitably small cost matrix that lead to to problem, as using random cost matrices of sizes between 3*5 and 15*20 never lead to it. When using lapmod in my storm-tracking algorithm, the numbers of rows and columns varies between close to zero and more than 5000. 
I did discover however that changing the type of the cost matrix from np.float64 to np.float32 lead in fewer cases to the problem. Maybe does this give you a hint at the cause of the problem?

I will perform extra tests to obtain a suitable cost matrix with very slow convergence, and post it if I find one.

**Comment by gatagat** [comment]
It is hard to tell without the data. Once you have some suitable cost matrix, let me know.

**Comment by Bram94** [comment]
In the mean time I have found some matrices that lead to a lack of convergence by running the storm-tracking algorithm. The smallest one has a size of 40*46, and the links below provide the corresponding arrays. The first gives the complete matrix, with unallowed associations indicated by a -1. The other 3 give the arrays cc, ii and jj, as required as input by your function prepare_sparse_cost. The cost_limit used is 1e3. 
Finally, I have attached the Python script that I used to run the algorithm. 

I hope that this example helps you to find the problem.

[cost_matrix_masked_error2.txt](https://github.com/gatagat/lapjv/files/1146481/cost_matrix_masked_error2.txt)
[cc_error2.txt](https://github.com/gatagat/lapjv/files/1146482/cc_error2.txt)
[ii_error2.txt](https://github.com/gatagat/lapjv/files/1146483/ii_error2.txt)
[jj_error2.txt](https://github.com/gatagat/lapjv/files/1146484/jj_error2.txt)
[lapmod_test.txt](https://github.com/gatagat/lapjv/files/1146496/lapmod_test.txt)

**Comment by Bram94** [comment]
Currently I convert the costs from floats between 0 and 1 to integers between 0 and 10^4, and thus far this hasn't given me the problem anymore. For me this solution suffices, if the problem is indeed circumvented by it. If it appears that it isn't, then I will note it.

Thanks for your help.

**Comment by gatagat** [comment]
Happy to hear that, I will have a look at it anyhow. Thanks for providing the test case!

**Comment by gatagat** [comment]
I could reproduce the bug when calling lapmod with your data (i mean the data loaded from the file, the data pasted here works just fine for me). This should be now fixed.

However, I could not reproduce the bug with lapjv. If you come accross some data that triggers slow convergence in lapjv, file a new ticket.

Thanks for the help.
