### ISSUE TITLE
Memory leak present in lapmod implementation

### ISSUE THREAD

**Issue by Bram94** [gatagat/lapjv#5]
There appears to be a memory leak in the lapmod implementation, as the memory usage keeps increasing when continuing running the algorithm (I have excluded other causes). Any series of large matrices (say 5000*5000) appears to be suited to get the problem, and can therefore be used for testing.

**Comment by Bram94** [comment]
I will do so

**Comment by Bram94** [comment]
Here is the Valgrind output and my test script for lapmod. I don't have experience with Valgrind, and I therefore find it hard to judge whether the output is useful.

[valgrind_output.txt](https://github.com/gatagat/lapjv/files/1158765/valgrid_output.txt)
[cell_test_lapmod.txt](https://github.com/gatagat/lapjv/files/1158766/cell_test_lapmod.txt)

**Comment by gatagat** [comment]
Thanks.

**Comment by Bram94** [comment]
The problem is indeed solved. Thanks!
